---
galaxy_info:
    author: Proxaform Orchestrator
    description: Deploys Portainer CE container management platform.
    license: MIT
    min_ansible_version: "2.12"
    platforms:
        - name: Ubuntu
          versions:
              - focal
              - jammy
              - noble
        - name: Debian
          versions:
              - bookworm

dependencies:
    - role: docker_host
