---
galaxy_info:
    author: Proxaform Orchestrator
    description: Deploys a prebuilt Technitium binary on a server after installing the .NET framework.
    license: MIT
    min_ansible_version: "2.12"
    platforms:
        - name: Ubuntu
          versions:
              - focal
              - jammy
              - noble
        - name: Debian
          versions:
              - bookworm
