---
galaxy_info:
    author: Proxaform Orchestrator
    description: Install and configure crontab-ui on a container running node
    license: MIT
    min_ansible_version: "2.12"
    platforms:
        - name: Ubuntu
          versions:
              - focal
              - jammy
              - noble
        - name: Debian
          versions:
              - bookworm

dependencies: [nodejs]
